<?PHP 
// 1. DATA PREPARATION
$RAW = $DATA['DATA'] ?? $DATA ?? [];
$SOURCE = $_GET['SOURCE'] ?? 'DRAMABOX'; 

IF (ISSET($RAW['DRAMAINFO'])) {
    $INFO = $RAW['DRAMAINFO'];
    $CHAPTERS = $RAW['CHAPTERS'] ?? [];
} ELSE {
    $INFO = $RAW; 
    $CHAPTERS = $RAW['CHAPTERS'] ?? $RAW['CHAPTER_LIST'] ?? []; 
}

$URLTITLE = ISSET($_GET['TITLE']) ? URLDECODE($_GET['TITLE']) : '';
$URLCOVER = ISSET($_GET['COVER']) ? URLDECODE($_GET['COVER']) : '';
$TITLE = !EMPTY($URLTITLE) ? $URLTITLE : ($INFO['BOOKNAME'] ?? $INFO['TITLE'] ?? 'NONTON DRAMA');
$RAWCOVER = !EMPTY($URLCOVER) ? $URLCOVER : ($INFO['COVER'] ?? $INFO['THUMBNAIL'] ?? '');

IF (STRPOS($RAWCOVER, '.HEIC') !== FALSE) {
    $CLEANURL = STR_REPLACE(['HTTP://', 'HTTPS://'], '', $RAWCOVER);
    $COVER = 'HTTPS://WSRV.NL/?URL=' . URLENCODE($CLEANURL) . '&OUTPUT=JPG&Q=80';
} ELSE {
    $COVER = STR_REPLACE('HTTP://', 'HTTPS://', $RAWCOVER);
}

$INTRO = $INFO['INTRODUCTION'] ?? $INFO['ABSTRACT'] ?? 'DESKRIPSI TIDAK TERSEDIA.';
$RATING = $INFO['SCORE'] ?? '5.0';
$VIEWS = NUMBER_FORMAT($INFO['FOLLOWCOUNT'] ?? $INFO['READ_COUNT'] ?? 0);
$TAGS = $INFO['TAGS'] ?? $INFO['STAT_INFOS'] ?? [];

// 2. AUTHENTICATION & LIMITS
REQUIRE_ONCE 'APP/AUTH.PHP';
$AUTH = NEW AUTH();
$ISLOGGEDIN = ISSET($_SESSION['USER_ID']); 
$ISVIP = $AUTH->ISVIP();
$URLID = $_GET['ID'] ?? '';

IF ($ISVIP) { $EPISODELIMIT = 99999; $USERSTATUS = 'VIP'; } 
ELSEIF ($ISLOGGEDIN) { $EPISODELIMIT = 20; $USERSTATUS = 'FREE'; } 
ELSE { $EPISODELIMIT = 10; $USERSTATUS = 'GUEST'; }

// 3. DATABASE SYNC (SAFE MODE)
$LASTEPDB = 0; $ISBOOKMARKED = FALSE;
IF ($ISLOGGEDIN && $URLID) {
    TRY {
        $DB = (NEW DATABASE())->GETCONNECTION();
        $STMT = $DB->PREPARE("SELECT EPISODE FROM HISTORY WHERE USER_ID = ? AND BOOK_ID = ?");
        $STMT->EXECUTE([$_SESSION['USER_ID'], $URLID]);
        $ROW = $STMT->FETCH(PDO::FETCH_ASSOC);
        IF($ROW) $LASTEPDB = $ROW['EPISODE'];

        $STMTFAV = $DB->PREPARE("SELECT ID FROM FAVORITES WHERE USER_ID = ? AND BOOK_ID = ?");
        $STMTFAV->EXECUTE([$_SESSION['USER_ID'], $URLID]);
        IF($STMTFAV->ROWCOUNT() > 0) $ISBOOKMARKED = TRUE;
    } CATCH (EXCEPTION $E) {}
}

GLOBAL $WEBCONFIG;
?>

<SCRIPT SRC="HTTPS://CDN.JSDELIVR.NET/NPM/HLS.JS@LATEST"></SCRIPT>

<DIV CLASS="THEATER-BG" STYLE="BACKGROUND-IMAGE: URL('<?= $COVER ?>')"></DIV>

<DIV CLASS="THEATER-CONTAINER FADE-IN" ID="THEATERCONTAINER">
    
    <DIV CLASS="PLAYER-WRAPPER">
        <DIV CLASS="VIDEO-FRAME" ID="VIDEOFRAME">
            <DIV ID="LOADINGSPINNER" CLASS="LOADING-OVERLAY" STYLE="DISPLAY:NONE;">
                <DIV CLASS="SPINNER"></DIV><P STYLE="MARGIN-TOP:15PX; COLOR:#FFF;">MEMUAT VIDEO...</P>
            </DIV>
            <VIDEO ID="MAINPLAYER" CONTROLS POSTER="<?= $COVER ?>" CLASS="CUSTOM-VIDEO" PLAYSINLINE></VIDEO>
            
            <DIV ID="PLAYEROVERLAY" CLASS="PAYWALL-OVERLAY" STYLE="DISPLAY: NONE;">
                <DIV CLASS="PAYWALL-CONTENT">
                    <I ID="OVERLAYICON" CLASS="RI-LOCK-2-FILL ICON-LOCK"></I>
                    <H2 ID="OVERLAYTITLE">KONTEN TERKUNCI</H2>
                    <P ID="OVERLAYDESC">UPGRADE VIP UNTUK MELANJUTKAN.</P>
                    <DIV ID="OVERLAYBUTTONS" CLASS="PAYWALL-ACTIONS">
                        <A HREF="/LOGIN" ID="BTNLOGINOVERLAY" CLASS="BTN-SECONDARY" STYLE="DISPLAY:NONE; MARGIN-RIGHT:10PX;">LOGIN GRATIS</A>
                        <A HREF="/DASHBOARD/BILLING" CLASS="BTN-UPGRADE">BELI VIP</A>
                    </DIV>
                </DIV>
            </DIV>
        </DIV>

        <?PHP IF(!EMPTY($WEBCONFIG['AD_PLAYER']) && !$ISVIP): ?>
        <DIV CLASS="AD-PLAYER-SLOT">
            <SMALL>IKLAN SPONSOR (HILANG JIKA VIP)</SMALL>
            <DIV CLASS="AD-CONTENT"><?= $WEBCONFIG['AD_PLAYER'] ?></DIV>
        </DIV>
        <?PHP ENDIF; ?>

        <DIV CLASS="PLAYER-TOOLBAR">
            <DIV CLASS="TOOLBAR-GROUP TOOLBAR-LEFT">
                <DIV CLASS="SKIP-CONTROLS">
                    <BUTTON ONCLICK="SKIPTIME(-10)" CLASS="TOOL-BTN BTN-CONTROL" TITLE="MUNDUR 10S">
                        <I CLASS="RI-REPLAY-10-LINE"></I> <SPAN CLASS="LABEL-TEXT">-10S</SPAN>
                    </BUTTON>
                    <BUTTON ONCLICK="SKIPTIME(10)" CLASS="TOOL-BTN BTN-CONTROL" TITLE="MAJU 10S">
                        <I CLASS="RI-FORWARD-10-LINE"></I> <SPAN CLASS="LABEL-TEXT">+10S</SPAN>
                    </BUTTON>
                </DIV>
                <LABEL CLASS="SWITCH-TOGGLE" TITLE="OTOMATIS PUTAR EPISODE SELANJUTNYA">
                    <INPUT TYPE="CHECKBOX" ID="AUTONEXT" CHECKED>
                    <SPAN CLASS="SLIDER"></SPAN>
                    <SPAN CLASS="LABEL-TEXT">AUTO NEXT</SPAN>
                </LABEL>
            </DIV>

            <DIV CLASS="TOOLBAR-GROUP TOOLBAR-RIGHT">
                <SELECT ID="SPEEDSELECT" ONCHANGE="CHANGESPEED(THIS)" CLASS="TOOL-SELECT">
                    <OPTION VALUE="1.0" SELECTED>1.0X</OPTION>
                    <OPTION VALUE="1.25">1.25X</OPTION>
                    <OPTION VALUE="1.5">1.5X</OPTION>
                    <OPTION VALUE="2.0">2.0X</OPTION>
                </SELECT>
                <DIV CLASS="DIVIDER-VERTICAL"></DIV>
                <DIV CLASS="VIEW-MODES">
                    <BUTTON ONCLICK="TOGGLEPIP()" CLASS="TOOL-BTN BTN-VIEW" TITLE="PIP">
                        <I CLASS="RI-PICTURE-IN-PICTURE-2-LINE"></I> <SPAN CLASS="LABEL-TEXT">PIP</SPAN>
                    </BUTTON>
                    <BUTTON ONCLICK="TOGGLECINEMA()" CLASS="TOOL-BTN BTN-VIEW" ID="BTNCINEMA" TITLE="CINEMA">
                        <I CLASS="RI-ASPECT-RATIO-LINE"></I> <SPAN CLASS="LABEL-TEXT">CINEMA</SPAN>
                    </BUTTON>
                    <BUTTON ONCLICK="TOGGLEFULLSCREEN()" CLASS="TOOL-BTN BTN-VIEW" TITLE="FULL">
                        <I CLASS="RI-FULLSCREEN-LINE"></I> <SPAN CLASS="LABEL-TEXT">FULL</SPAN>
                    </BUTTON>
                </DIV>
                <DIV CLASS="DIVIDER-VERTICAL"></DIV>
                <DIV CLASS="ACTION-BUTTONS">
                    <BUTTON ONCLICK="TOGGLEBOOKMARK()" CLASS="TOOL-BTN BTN-ACTION" ID="BTNBOOKMARK" TITLE="SIMPAN">
                        <I CLASS="RI-BOOKMARK-LINE"></I> <SPAN CLASS="LABEL-TEXT">SIMPAN</SPAN>
                    </BUTTON>
                    <BUTTON ONCLICK="REPORTVIDEO()" CLASS="TOOL-BTN BTN-DANGER REPORT-BTN" TITLE="LAPOR">
                        <I CLASS="RI-ALARM-WARNING-LINE"></I> <SPAN CLASS="LABEL-TEXT">LAPOR</SPAN>
                    </BUTTON>
                </DIV>
            </DIV>
        </DIV>

        <DIV CLASS="PLAYER-NAV-CONTROLS">
            <BUTTON ID="BTNPREV" ONCLICK="NAVEPISODE(-1)" CLASS="NAV-BTN DISABLED" DISABLED><I CLASS="RI-SKIP-BACK-FILL"></I> PREV</BUTTON>
            <BUTTON ID="BTNNEXT" ONCLICK="NAVEPISODE(1)" CLASS="NAV-BTN">NEXT <I CLASS="RI-SKIP-FORWARD-FILL"></I></BUTTON>
        </DIV>

        <DIV CLASS="VIDEO-INFO">
            <H1 CLASS="DRAMA-TITLE"><?= HTMLSPECIALCHARS($TITLE) ?></H1>
            <DIV CLASS="META-BADGES">
                <SPAN CLASS="BADGE-SERVER">SERVER: <?= STRTOUPPER($SOURCE) ?></SPAN>
                <SPAN CLASS="BADGE-RATING"><I CLASS="RI-STAR-FILL"></I> <?= $RATING ?></SPAN>
                <SPAN CLASS="BADGE-INFO"><I CLASS="RI-EYE-LINE"></I> <?= $VIEWS ?></SPAN>
                <SPAN CLASS="BADGE-INFO"><I CLASS="RI-FILM-LINE"></I> <?= COUNT($CHAPTERS) ?> EPS</SPAN>
                <?PHP IF($ISVIP): ?>
                    <SPAN CLASS="BADGE-STATUS STATUS-VIP"><I CLASS="RI-VIP-CROWN-FILL"></I> VIP</SPAN>
                <?PHP ELSEIF($ISLOGGEDIN): ?>
                    <SPAN CLASS="BADGE-STATUS STATUS-FREE"><I CLASS="RI-USER-SMILE-LINE"></I> FREE</SPAN>
                <?PHP ELSE: ?>
                    <SPAN CLASS="BADGE-STATUS STATUS-GUEST"><I CLASS="RI-USER-LINE"></I> TAMU</SPAN>
                <?PHP ENDIF; ?>
            </DIV>
            <?PHP IF(!EMPTY($TAGS)): ?>
            <DIV CLASS="TAGS-CONTAINER">
                <?PHP FOREACH($TAGS AS $T) { IF(!IS_ARRAY($T)) ECHO "<A HREF='/?PAGE=SEARCH&Q=".URLENCODE(TRIM($T))."&SOURCE=$SOURCE' CLASS='TAG-PILL'>".HTMLSPECIALCHARS(TRIM($T))."</A>"; } ?>
            </DIV>
            <?PHP ENDIF; ?>
            <DIV CLASS="SYNOPSIS-BOX">
                <H3>SINOPSIS</H3>
                <P><?= NL2BR(HTMLSPECIALCHARS($INTRO)) ?></P>
            </DIV>
        </DIV>
    </DIV>

    <DIV CLASS="PLAYLIST-WRAPPER" ID="PLAYLISTWRAPPER">
        <DIV CLASS="PLAYLIST-HEADER">
            <H3>DAFTAR EPISODE</H3>
            <DIV CLASS="PH-SEARCH"><I CLASS="RI-SEARCH-LINE"></I><INPUT TYPE="TEXT" ID="EPSSEARCH" PLACEHOLDER="CARI..." ONKEYUP="FILTEREPISODES()"></DIV>
        </DIV>
        <DIV CLASS="PLAYLIST-SCROLL" ID="PLAYLISTCONTAINER">
            <?PHP IF(!EMPTY($CHAPTERS)): ?>
                <?PHP FOREACH($CHAPTERS AS $IDX => $CHAP): 
                    $NUM = $IDX + 1;
                    $ISLOCKED = ($NUM > $EPISODELIMIT); 
                    $VIDID = ($SOURCE === 'MELOLO') ? ($CHAP['VID'] ?? $CHAP['ID'] ?? '') : '';
                    $VIDEOURL = ($SOURCE !== 'MELOLO') ? ($CHAP['MP4'] ?? $CHAP['URL'] ?? '') : '';
                    $HASLINK = !EMPTY($VIDID) || !EMPTY($VIDEOURL);
                ?>
                <BUTTON ONCLICK="PLAYEPISODE('<?= $VIDEOURL ?>', '<?= $VIDID ?>', <?= $ISLOCKED?'TRUE':'FALSE' ?>, <?= $HASLINK?'TRUE':'FALSE' ?>, THIS, <?= $NUM ?>)" 
                        CLASS="EPS-ITEM" DATA-NUM="<?= $NUM ?>" ID="EPS-BTN-<?= $NUM ?>">
                    <DIV CLASS="EPS-LEFT"><SPAN CLASS="EPS-NUM"><?= STR_PAD($NUM, 2, '0', STR_PAD_LEFT) ?></SPAN><DIV CLASS="PLAYING-ANIM"><SPAN></SPAN><SPAN></SPAN><SPAN></SPAN></DIV></DIV>
                    <DIV CLASS="EPS-DETAILS">
                        <SPAN CLASS="EPS-NAME">EPISODE <?= $NUM ?></SPAN>
                        <SPAN CLASS="BADGE-STATUS <?= $ISLOCKED ? 'STATUS-LOCK' : 'STATUS-OK' ?>">
                            <?= $ISLOCKED ? '<I CLASS="RI-LOCK-FILL"></I> TERKUNCI' : '<I CLASS="RI-PLAY-CIRCLE-LINE"></I> PUTAR' ?>
                        </SPAN>
                    </DIV>
                    <DIV CLASS="WATCHED-INDICATOR"><I CLASS="RI-EYE-FILL"></I></DIV>
                </BUTTON>
                <?PHP ENDFOREACH; ?>
            <?PHP ELSE: ?>
                <DIV STYLE="PADDING:40PX 20PX; TEXT-ALIGN:CENTER; COLOR:#666;">BELUM ADA EPISODE.</DIV>
            <?PHP ENDIF; ?>
        </DIV>
    </DIV>

    <DIV CLASS="COMMENTS-SECTION">
        <DIV CLASS="COMMENTS-HEADER">
            <H3><I CLASS="RI-CHAT-VOICE-LINE"></I> DISKUSI PENONTON</H3>
            <SPAN CLASS="COMMENTS-COUNT">TANYA JAWAB, SPOILER, & REQUEST DISINI.</SPAN>
        </DIV>

        <DIV CLASS="COMMENT-FORM">
            <DIV CLASS="FORM-INPUT-WRAPPER">
                <TEXTAREA ID="COMMENTMSG" ROWS="2" PLACEHOLDER="TULIS KOMENTAR... (SPOILER PAKAI TAG [SPOILER])" 
                          <?= !$ISLOGGEDIN ? 'READONLY ONCLICK="ASKLOGIN()"' : '' ?>></TEXTAREA>
                <BUTTON ONCLICK="<?= $ISLOGGEDIN ? 'POSTCOMMENT()' : 'ASKLOGIN()' ?>" CLASS="BTN-SEND">
                    <I CLASS="RI-SEND-PLANE-FILL"></I> KIRIM
                </BUTTON>
            </DIV>
        </DIV>

        <DIV ID="COMMENTSLIST" CLASS="COMMENTS-LIST">
            <DIV STYLE="TEXT-ALIGN:CENTER; PADDING:20PX; COLOR:#666;">
                <DIV CLASS="SPINNER" STYLE="WIDTH:20PX; HEIGHT:20PX; MARGIN:0 AUTO 10PX;"></DIV> MEMUAT KOMENTAR...
            </DIV>
        </DIV>
    </DIV>

</DIV>

<SCRIPT>
VAR DRAMAID = '<?= $URLID ?>'; 
VAR CURRENTSOURCE = '<?= $SOURCE ?>';
VAR DRAMATITLE = '<?= ADDSLASHES($TITLE) ?>';
VAR LASTEPSERVER = <?= INTVAL($LASTEPDB) ?>; 
VAR DRAMACOVER = '<?= ADDSLASHES($COVER) ?>';
VAR TOTALEPS = <?= COUNT($CHAPTERS) ?>;
VAR ISLOGGEDIN = <?= $ISLOGGEDIN ? 'TRUE' : 'FALSE' ?>;
VAR USERSTATUS = '<?= $USERSTATUS ?>'; 
VAR ISFAV = <?= $ISBOOKMARKED ? 'TRUE' : 'FALSE' ?>;

VAR VIDEO = DOCUMENT.GETELEMENTBYID('MAINPLAYER');
VAR HLS = NULL;
VAR CURRENTEPNUM = 0;

DOCUMENT.ADDEVENTLISTENER('DOMCONTENTLOADED', FUNCTION() {
    LOADHISTORY(); 
    UPDATEBOOKMARKBTN(ISFAV);
    LOADCOMMENTS(); // LOAD KOMENTAR
    
    VAR STARTEP = 1;
    IF (LASTEPSERVER > 0) STARTEP = LASTEPSERVER;
    ELSE {
        VAR LOCALLAST = GETLASTWATCHEDEP();
        IF (LOCALLAST > 0) STARTEP = LOCALLAST;
    }
    VAR BTN = DOCUMENT.GETELEMENTBYID('EPS-BTN-' + STARTEP);
    IF(BTN) { BTN.CLICK(); SETTIMEOUT(() => BTN.SCROLLINTOVIEW({BEHAVIOR: 'SMOOTH', BLOCK: 'CENTER'}), 500); }
    ELSE { VAR FIRST = DOCUMENT.QUERYSELECTOR('.EPS-ITEM'); IF(FIRST) FIRST.CLICK(); }
});

// --- KOMENTAR LOGIC ---
FUNCTION LOADCOMMENTS() {
    FETCH('/INDEX.PHP?PAGE=API_LOAD_COMMENTS&ID=' + DRAMAID)
    .THEN(RES => RES.JSON())
    .THEN(DATA => {
        LET HTML = '';
        IF(DATA.LENGTH === 0) {
            HTML = '<DIV STYLE="TEXT-ALIGN:CENTER; COLOR:#666; PADDING:20PX;">BELUM ADA KOMENTAR. JADILAH YANG PERTAMA!</DIV>';
        } ELSE {
            DATA.FOREACH(C => {
                LET INITIAL = C.USERNAME.CHARAT(0).TOUPPERCASE();
                LET AVATAR = C.AVATAR ? `<IMG SRC="${C.AVATAR}" CLASS="C-AVATAR-IMG">` : `<DIV CLASS="C-AVATAR-DEF">${INITIAL}</DIV>`;
                LET BADGE = C.ROLE === 'ADMIN' ? '<SPAN CLASS="C-BADGE ADMIN">ADMIN</SPAN>' : (C.ROLE === 'VIP' ? '<SPAN CLASS="C-BADGE VIP">VIP</SPAN>' : '');
                
                HTML += `
                <DIV CLASS="COMMENT-ITEM">
                    <DIV CLASS="C-HEAD">
                        ${AVATAR}
                        <DIV CLASS="C-META">
                            <SPAN CLASS="C-NAME">${C.FULLNAME || C.USERNAME} ${BADGE}</SPAN>
                            <SPAN CLASS="C-DATE">${NEW DATE(C.CREATED_AT).TOLOCALEDATESTRING()}</SPAN>
                        </DIV>
                    </DIV>
                    <DIV CLASS="C-BODY">${C.MESSAGE}</DIV>
                </DIV>`;
            });
        }
        DOCUMENT.GETELEMENTBYID('COMMENTSLIST').INNERHTML = HTML;
    });
}

FUNCTION POSTCOMMENT() {
    LET MSG = DOCUMENT.GETELEMENTBYID('COMMENTMSG').VALUE;
    IF(!MSG.TRIM()) RETURN ALERT("KOMENTAR TIDAK BOLEH KOSONG!");
    
    LET BTN = DOCUMENT.QUERYSELECTOR('.BTN-SEND');
    LET OLDTEXT = BTN.INNERHTML;
    BTN.INNERHTML = '<I CLASS="RI-LOADER-4-LINE SPIN"></I>';
    BTN.DISABLED = TRUE;

    FETCH('/INDEX.PHP?PAGE=API_POST_COMMENT', {
        METHOD: 'POST', 
        BODY: JSON.STRINGIFY({ID: DRAMAID, MSG: MSG})
    })
    .THEN(RES => RES.JSON())
    .THEN(D => {
        IF(D.STATUS) {
            DOCUMENT.GETELEMENTBYID('COMMENTMSG').VALUE = '';
            LOADCOMMENTS(); 
        } ELSE {
            ALERT(D.MSG || 'GAGAL MENGIRIM KOMENTAR.');
        }
        BTN.INNERHTML = OLDTEXT;
        BTN.DISABLED = FALSE;
    });
}

FUNCTION ASKLOGIN() {
    IF(CONFIRM("ANDA HARUS LOGIN UNTUK BERKOMENTAR. LOGIN SEKARANG?")) {
        WINDOW.LOCATION.HREF = '/LOGIN';
    }
}

// --- PLAYER LOGIC ---
FUNCTION PLAYEPISODE(DIRECTURL, VIDID, ISLOCKED, HASLINK, BTN, EPSNUM) {
    CURRENTEPNUM = EPSNUM;
    DOCUMENT.GETELEMENTBYID('LOADINGSPINNER').STYLE.DISPLAY = 'FLEX';
    DOCUMENT.GETELEMENTBYID('PLAYEROVERLAY').STYLE.DISPLAY = 'NONE';
    DOCUMENT.QUERYSELECTORALL('.EPS-ITEM').FOREACH(B => B.CLASSLIST.REMOVE('ACTIVE'));
    
    IF(BTN) { BTN.CLASSLIST.ADD('ACTIVE'); MARKASWATCHED(EPSNUM); UPDATENAVBUTTONS(BTN); }
    VIDEO.STYLE.DISPLAY = 'BLOCK'; VIDEO.PAUSE();
    VAR RESUMETIME = LOCALSTORAGE.GETITEM('RESUME_' + DRAMAID + '_' + EPSNUM);

    IF (ISLOCKED) { 
        LET TITLE = 'KONTEN TERKUNCI'; LET DESC = 'UPGRADE VIP UNTUK MELANJUTKAN.'; LET SHOWLOGINBTN = FALSE;
        IF (USERSTATUS === 'GUEST') { TITLE = 'BATAS TAMU (10 EPS)'; DESC = 'LOGIN UNTUK NONTON GRATIS S/D EP 20.'; SHOWLOGINBTN = TRUE; } 
        ELSE IF (USERSTATUS === 'FREE') { TITLE = 'JATAH GRATIS HABIS'; DESC = 'BELI VIP UNTUK AKSES PENUH.'; }
        SHOWOVERLAY('RI-LOCK-STAR-FILL', '#FFD700', TITLE, DESC, TRUE, SHOWLOGINBTN); RETURN; 
    }
    IF (!HASLINK) { SHOWOVERLAY('RI-FILE-SHRED-LINE', '#666', 'BELUM TERSEDIA', 'EPISODE BELUM RILIS.', FALSE, FALSE); RETURN; }

    IF (CURRENTSOURCE === 'MELOLO' && VIDID) {
        FETCH(`/INDEX.PHP?PAGE=API_GET_STREAM&SOURCE=MELOLO&ID=${VIDID}`)
            .THEN(RES => RES.JSON())
            .THEN(RESP => {
                LET STREAMURL = RESP.MAIN_URL || RESP.DATA?.MAIN_URL || RESP.URL || '';
                IF(STREAMURL) {
                    IF (STREAMURL.STARTSWITH('HTTP://')) STREAMURL = STREAMURL.REPLACE('HTTP://', 'HTTPS://');
                    LOADVIDEO(STREAMURL, RESUMETIME);
                } ELSE { SHOWOVERLAY('RI-ERROR-WARNING-LINE', '#FF4757', 'GAGAL', 'VIDEO ERROR.', FALSE, FALSE); }
            })
            .CATCH(() => SHOWOVERLAY('RI-WIFI-OFF-LINE', '#FF4757', 'ERROR', 'GAGAL KONEKSI.', FALSE, FALSE));
    } ELSE { LOADVIDEO(DIRECTURL, RESUMETIME); }
}

FUNCTION LOADVIDEO(URL, STARTTIME) {
    IF(!URL) { DOCUMENT.GETELEMENTBYID('LOADINGSPINNER').STYLE.DISPLAY = 'NONE'; RETURN; }
    FUNCTION ONREADY() {
        DOCUMENT.GETELEMENTBYID('LOADINGSPINNER').STYLE.DISPLAY = 'NONE';
        IF(STARTTIME) VIDEO.CURRENTTIME = PARSEFLOAT(STARTTIME);
        VIDEO.PLAY().CATCH(E => CONSOLE.LOG("AUTOPLAY BLOCKED"));
    }
    IF (HLS.ISSUPPORTED() && URL.INCLUDES('.M3U8')) {
        IF(HLS) HLS.DESTROY();
        HLS = NEW HLS(); HLS.LOADSOURCE(URL); HLS.ATTACHMEDIA(VIDEO);
        HLS.ON(HLS.EVENTS.MANIFEST_PARSED, ONREADY);
    } ELSE {
        VIDEO.SRC = URL; VIDEO.ADDEVENTLISTENER('LOADEDMETADATA', ONREADY, {ONCE:TRUE}); VIDEO.PLAY().CATCH(E=>{});
    }
}

FUNCTION TOGGLEBOOKMARK() {
    IF (!ISLOGGEDIN) { IF(CONFIRM("LOGIN DULU UNTUK MENYIMPAN DRAMA INI.")) WINDOW.LOCATION.HREF = '/LOGIN'; RETURN; }
    ISFAV = !ISFAV; UPDATEBOOKMARKBTN(ISFAV);
    FETCH('/INDEX.PHP?PAGE=API_TOGGLE_FAV', { METHOD: 'POST', HEADERS: { 'CONTENT-TYPE': 'APPLICATION/JSON' }, BODY: JSON.STRINGIFY({ ID: DRAMAID, TITLE: DRAMATITLE, COVER: DRAMACOVER }) })
    .THEN(RES => RES.JSON()).THEN(DATA => { IF(!DATA.STATUS) { ISFAV = !ISFAV; UPDATEBOOKMARKBTN(ISFAV); ALERT("GAGAL: " + DATA.MSG); } });
}
FUNCTION UPDATEBOOKMARKBTN(STATUS) {
    CONST BTN = DOCUMENT.GETELEMENTBYID('BTNBOOKMARK');
    CONST ICON = BTN.QUERYSELECTOR('I'); CONST LABEL = BTN.QUERYSELECTOR('.LABEL-TEXT');
    IF (STATUS) { BTN.CLASSLIST.ADD('ACTIVE-BOOKMARK'); ICON.CLASSNAME = 'RI-BOOKMARK-FILL'; LABEL.INNERTEXT = 'TERSIMPAN'; } 
    ELSE { BTN.CLASSLIST.REMOVE('ACTIVE-BOOKMARK'); ICON.CLASSNAME = 'RI-BOOKMARK-LINE'; LABEL.INNERTEXT = 'SIMPAN'; }
}
FUNCTION MARKASWATCHED(NUM) {
    IF(!DRAMAID) RETURN;
    VAR K = 'WATCHED_' + DRAMAID; VAR H = JSON.PARSE(LOCALSTORAGE.GETITEM(K) || '[]');
    IF(!H.INCLUDES(NUM)) { H.PUSH(NUM); LOCALSTORAGE.SETITEM(K, JSON.STRINGIFY(H)); }
    LOCALSTORAGE.SETITEM('HISTORY_ITEM_' + DRAMAID, JSON.STRINGIFY({ ID: DRAMAID, TITLE: DRAMATITLE, COVER: DRAMACOVER, LASTEP: NUM, TIMESTAMP: DATE.NOW(), SOURCE: CURRENTSOURCE }));
    VAR BTN = DOCUMENT.GETELEMENTBYID('EPS-BTN-' + NUM); IF(BTN) BTN.CLASSLIST.ADD('WATCHED');
    IF (ISLOGGEDIN) {
        FETCH('/INDEX.PHP?PAGE=API_SAVE_HISTORY', { METHOD: 'POST', HEADERS: { 'CONTENT-TYPE': 'APPLICATION/JSON' }, BODY: JSON.STRINGIFY({ ID: DRAMAID, TITLE: DRAMATITLE, COVER: DRAMACOVER, EPISODE: NUM, TOTAL: TOTALEPS }) });
    }
}
FUNCTION LOADHISTORY() {
    IF(!DRAMAID) RETURN;
    VAR LOCALDATA = JSON.PARSE(LOCALSTORAGE.GETITEM('WATCHED_' + DRAMAID) || '[]');
    IF (LASTEPSERVER > 0 && !LOCALDATA.INCLUDES(LASTEPSERVER)) { LOCALDATA.PUSH(LASTEPSERVER); LOCALSTORAGE.SETITEM('WATCHED_' + DRAMAID, JSON.STRINGIFY(LOCALDATA)); }
    LOCALDATA.FOREACH(N => { VAR BTN = DOCUMENT.GETELEMENTBYID('EPS-BTN-' + N); IF(BTN) BTN.CLASSLIST.ADD('WATCHED'); });
}
FUNCTION GETLASTWATCHEDEP() { VAR H = JSON.PARSE(LOCALSTORAGE.GETITEM('HISTORY_ITEM_' + DRAMAID) || '{}'); RETURN H.LASTEP || 0; }
VIDEO.ADDEVENTLISTENER('TIMEUPDATE', FUNCTION() { IF(VIDEO.CURRENTTIME > 5 && !VIDEO.PAUSED && CURRENTEPNUM > 0) LOCALSTORAGE.SETITEM('RESUME_' + DRAMAID + '_' + CURRENTEPNUM, VIDEO.CURRENTTIME); });
VIDEO.ADDEVENTLISTENER('ENDED', FUNCTION() { IF(DOCUMENT.GETELEMENTBYID('AUTONEXT').CHECKED) NAVEPISODE(1); });
FUNCTION SKIPTIME(S) { VIDEO.CURRENTTIME += S; }
FUNCTION CHANGESPEED(EL) { VIDEO.PLAYBACKRATE = PARSEFLOAT(EL.VALUE); }
FUNCTION TOGGLECINEMA() { DOCUMENT.GETELEMENTBYID('THEATERCONTAINER').CLASSLIST.TOGGLE('CINEMA-MODE'); DOCUMENT.GETELEMENTBYID('BTNCINEMA').CLASSLIST.TOGGLE('ACTIVE-VIEW'); }
FUNCTION TOGGLEFULLSCREEN() { IF (!DOCUMENT.FULLSCREENELEMENT) { VIDEO.REQUESTFULLSCREEN(); } ELSE { DOCUMENT.EXITFULLSCREEN(); } }
FUNCTION TOGGLEPIP() { IF (DOCUMENT.PICTUREINPICTUREELEMENT) { DOCUMENT.EXITPICTUREINPICTURE(); } ELSE IF (DOCUMENT.PICTUREINPICTUREENABLED) { VIDEO.REQUESTPICTUREINPICTURE(); } }
FUNCTION NAVEPISODE(DIR) { VAR CUR = DOCUMENT.QUERYSELECTOR('.EPS-ITEM.ACTIVE'); IF(!CUR) RETURN; VAR TARGET = DIR===1 ? CUR.NEXTELEMENTSIBLING : CUR.PREVIOUSELEMENTSIBLING; IF(TARGET) TARGET.CLICK(); }
FUNCTION UPDATENAVBUTTONS(BTN) { DOCUMENT.GETELEMENTBYID('BTNPREV').DISABLED = !BTN.PREVIOUSELEMENTSIBLING; DOCUMENT.GETELEMENTBYID('BTNNEXT').DISABLED = !BTN.NEXTELEMENTSIBLING; }
FUNCTION SHOWOVERLAY(ICON, COL, TITLE, DESC, SHOWVIPBTN, SHOWLOGINBTN) { 
    VAR OV = DOCUMENT.GETELEMENTBYID('PLAYEROVERLAY'); VIDEO.STYLE.DISPLAY = 'NONE'; VIDEO.PAUSE(); OV.STYLE.DISPLAY = 'FLEX'; 
    DOCUMENT.GETELEMENTBYID('OVERLAYICON').CLASSNAME = ICON; DOCUMENT.GETELEMENTBYID('OVERLAYICON').STYLE.COLOR = COL; 
    DOCUMENT.GETELEMENTBYID('OVERLAYTITLE').INNERTEXT = TITLE; DOCUMENT.GETELEMENTBYID('OVERLAYDESC').INNERTEXT = DESC; 
    DOCUMENT.GETELEMENTBYID('OVERLAYBUTTONS').STYLE.DISPLAY = 'BLOCK'; 
    DOCUMENT.GETELEMENTBYID('BTNLOGINOVERLAY').STYLE.DISPLAY = SHOWLOGINBTN ? 'INLINE-BLOCK' : 'NONE';
    DOCUMENT.QUERYSELECTOR('.BTN-UPGRADE').STYLE.DISPLAY = SHOWVIPBTN ? 'INLINE-BLOCK' : 'NONE';
    DOCUMENT.GETELEMENTBYID('LOADINGSPINNER').STYLE.DISPLAY = 'NONE'; 
}
FUNCTION FILTEREPISODES() { VAR V = DOCUMENT.GETELEMENTBYID('EPSSEARCH').VALUE.TOLOWERCASE(); DOCUMENT.QUERYSELECTORALL('.EPS-ITEM').FOREACH(EL => { VAR T = EL.INNERTEXT.TOLOWERCASE(); EL.STYLE.DISPLAY = T.INCLUDES(V) ? "" : "NONE"; }); }
FUNCTION REPORTVIDEO() { IF(CONFIRM("LAPOR VIDEO RUSAK?")) WINDOW.OPEN(`HTTPS://T.ME/JEJAKINTEL?TEXT=${ENCODEURICOMPONENT('LAPOR ERROR: '+DRAMATITLE+' EP '+CURRENTEPNUM)}`, '_BLANK'); }
</SCRIPT>

<STYLE>
/* STYLE KOMENTAR NATIVE */
.COMMENTS-SECTION { GRID-COLUMN: 1 / -1; MARGIN-TOP: 40PX; BACKGROUND: #151518; BORDER: 1PX SOLID RGBA(255,255,255,0.05); BORDER-RADIUS: 16PX; PADDING: 30PX; }
.COMMENTS-HEADER { BORDER-BOTTOM: 1PX SOLID RGBA(255,255,255,0.1); PADDING-BOTTOM: 20PX; MARGIN-BOTTOM: 20PX; DISPLAY: FLEX; ALIGN-ITEMS: CENTER; GAP: 15PX; }
.COMMENTS-HEADER H3 { MARGIN: 0; COLOR: WHITE; FONT-SIZE: 1.3REM; DISPLAY: FLEX; ALIGN-ITEMS: CENTER; GAP: 10PX; }
.COMMENTS-HEADER H3 I { COLOR: VAR(--PRIMARY); }
.COMMENTS-COUNT { COLOR: #888; FONT-SIZE: 0.9REM; MARGIN-TOP: 4PX; }

.COMMENT-FORM { MARGIN-BOTTOM: 25PX; }
.FORM-INPUT-WRAPPER { DISPLAY: FLEX; GAP: 10PX; ALIGN-ITEMS: FLEX-START; }
.FORM-INPUT-WRAPPER TEXTAREA { FLEX: 1; BACKGROUND: #0F1014; BORDER: 1PX SOLID RGBA(255,255,255,0.1); COLOR: WHITE; PADDING: 12PX; BORDER-RADIUS: 8PX; RESIZE: NONE; FONT-FAMILY: INHERIT; }
.FORM-INPUT-WRAPPER TEXTAREA:FOCUS { BORDER-COLOR: VAR(--PRIMARY); OUTLINE: NONE; }
.BTN-SEND { BACKGROUND: VAR(--PRIMARY); COLOR: WHITE; BORDER: NONE; PADDING: 0 20PX; HEIGHT: 50PX; BORDER-RADIUS: 8PX; CURSOR: POINTER; FONT-WEIGHT: BOLD; DISPLAY: FLEX; ALIGN-ITEMS: CENTER; GAP: 5PX; }
.BTN-SEND:HOVER { OPACITY: 0.9; }

.COMMENTS-LIST { DISPLAY: FLEX; FLEX-DIRECTION: COLUMN; GAP: 20PX; MAX-HEIGHT: 500PX; OVERFLOW-Y: AUTO; PADDING-RIGHT: 5PX; }
.COMMENT-ITEM { BACKGROUND: RGBA(255,255,255,0.02); PADDING: 15PX; BORDER-RADIUS: 10PX; BORDER: 1PX SOLID RGBA(255,255,255,0.05); }
.C-HEAD { DISPLAY: FLEX; GAP: 12PX; MARGIN-BOTTOM: 10PX; }
.C-AVATAR-IMG { WIDTH: 40PX; HEIGHT: 40PX; BORDER-RADIUS: 50%; OBJECT-FIT: COVER; }
.C-AVATAR-DEF { WIDTH: 40PX; HEIGHT: 40PX; BORDER-RADIUS: 50%; BACKGROUND: #333; COLOR: #FFF; DISPLAY: FLEX; ALIGN-ITEMS: CENTER; JUSTIFY-CONTENT: CENTER; FONT-WEIGHT: BOLD; }
.C-META { DISPLAY: FLEX; FLEX-DIRECTION: COLUMN; JUSTIFY-CONTENT: CENTER; }
.C-NAME { COLOR: #FFF; FONT-WEIGHT: 600; FONT-SIZE: 0.95REM; DISPLAY: FLEX; ALIGN-ITEMS: CENTER; GAP: 8PX; }
.C-DATE { COLOR: #666; FONT-SIZE: 0.75REM; }
.C-BODY { COLOR: #CCC; FONT-SIZE: 0.9REM; LINE-HEIGHT: 1.5; WHITE-SPACE: PRE-WRAP; }
.C-BADGE { FONT-SIZE: 0.65REM; PADDING: 2PX 6PX; BORDER-RADIUS: 4PX; FONT-WEIGHT: 800; }
.C-BADGE.ADMIN { BACKGROUND: #7C3AED; COLOR: #FFF; }
.C-BADGE.VIP { BACKGROUND: #FFD700; COLOR: #000; }
.COMMENTS-LIST::-WEBKIT-SCROLLBAR { WIDTH: 5PX; }
.COMMENTS-LIST::-WEBKIT-SCROLLBAR-THUMB { BACKGROUND: #333; BORDER-RADIUS: 10PX; }

/* STYLE PLAYER SEPERTI SEBELUMNYA */
.PLAYER-TOOLBAR { DISPLAY: FLEX; JUSTIFY-CONTENT: SPACE-BETWEEN; ALIGN-ITEMS: CENTER; FLEX-WRAP: WRAP; GAP: 15PX; BACKGROUND: #1A1B20; PADDING: 12PX 20PX; BORDER-RADIUS: 0 0 16PX 16PX; MARGIN-TOP: -5PX; BORDER-TOP: NONE; BOX-SHADOW: 0 5PX 15PX RGBA(0,0,0,0.3); }
.TOOLBAR-GROUP { DISPLAY: FLEX; ALIGN-ITEMS: CENTER; GAP: 8PX; }
.DIVIDER-VERTICAL { WIDTH: 2PX; HEIGHT: 24PX; BACKGROUND: RGBA(255,255,255,0.2); MARGIN: 0 8PX; BORDER-RADIUS: 2PX; }
.TOOL-BTN { BACKGROUND: RGBA(255,255,255,0.08); BORDER: 1PX SOLID RGBA(255,255,255,0.1); COLOR: #FFF; CURSOR: POINTER; DISPLAY: INLINE-FLEX; ALIGN-ITEMS: CENTER; JUSTIFY-CONTENT: CENTER; GAP: 8PX; PADDING: 8PX 14PX; TRANSITION: ALL 0.3S EASE; FONT-SIZE: 0.95REM; BORDER-RADIUS: 8PX; FONT-WEIGHT: 500; }
.TOOL-BTN:HOVER { COLOR: WHITE; BACKGROUND: RGBA(255,255,255,0.15); }
.TOOL-SELECT { BACKGROUND: RGBA(255,255,255,0.08); BORDER: 1PX SOLID RGBA(255,255,255,0.1); COLOR: #FFF; PADDING: 8PX 12PX; BORDER-RADIUS: 8PX; CURSOR: POINTER; FONT-SIZE: 0.9REM; OUTLINE: NONE; FONT-WEIGHT: 500; }
.TOOL-SELECT OPTION { BACKGROUND: #1A1B20; COLOR: #FFF; }
.BTN-VIEW:HOVER { BACKGROUND: RGBA(0, 210, 255, 0.2); COLOR: #00D2FF; BORDER-COLOR: #00D2FF; BOX-SHADOW: 0 0 10PX RGBA(0, 210, 255, 0.4); }
.BTN-VIEW.ACTIVE-VIEW { BACKGROUND: #00D2FF; COLOR: #000 !IMPORTANT; BORDER-COLOR: #00D2FF; FONT-WEIGHT: BOLD; BOX-SHADOW: 0 0 15PX RGBA(0, 210, 255, 0.6); }
.BTN-ACTION.ACTIVE-BOOKMARK { BACKGROUND: #E50914; COLOR: WHITE !IMPORTANT; BORDER: 1PX SOLID #E50914; BOX-SHADOW: 0 0 15PX RGBA(229, 9, 20, 0.6); }
.BTN-DANGER:HOVER { BACKGROUND: RGBA(255, 165, 0, 0.2); COLOR: #FFA500; BORDER-COLOR: #FFA500; BOX-SHADOW: 0 0 10PX RGBA(255, 165, 0, 0.4); }
.BADGE-STATUS { PADDING: 4PX 10PX; BORDER-RADIUS: 6PX; FONT-SIZE: 0.7REM; FONT-WEIGHT: 800; TEXT-TRANSFORM: UPPERCASE; DISPLAY: INLINE-FLEX; ALIGN-ITEMS: CENTER; GAP: 5PX; MARGIN-LEFT: AUTO; }
.BADGE-STATUS.STATUS-VIP { BACKGROUND: #FFD700; COLOR: #000; BORDER: 1PX SOLID #EAB308; }
.BADGE-STATUS.STATUS-FREE { BACKGROUND: #22C55E; COLOR: #FFF; BORDER: 1PX SOLID #16A34A; }
.BADGE-STATUS.STATUS-GUEST { BACKGROUND: #666; COLOR: #FFF; }
.BADGE-STATUS.STATUS-LOCK { BACKGROUND: #FFD700; COLOR: #000; BORDER: 1PX SOLID #EAB308; }
.BADGE-STATUS.STATUS-OK { BACKGROUND: #22C55E; COLOR: #FFF; BORDER: 1PX SOLID #16A34A; }
.WATCHED-INDICATOR { MARGIN-LEFT: 12PX; COLOR: #4ADE80; FONT-SIZE: 1.2REM; DISPLAY: NONE; }
.EPS-ITEM.WATCHED .WATCHED-INDICATOR { DISPLAY: BLOCK !IMPORTANT; }
.EPS-ITEM.WATCHED .EPS-NAME { COLOR: #888; }
.THEATER-BG { POSITION:FIXED; TOP:0; LEFT:0; WIDTH:100%; HEIGHT:100VH; BACKGROUND-SIZE:COVER; FILTER:BLUR(80PX) BRIGHTNESS(0.3); Z-INDEX:-1; }
.THEATER-CONTAINER { DISPLAY:GRID; GRID-TEMPLATE-COLUMNS:1FR 340PX; GAP:30PX; MAX-WIDTH:1400PX; MARGIN:0 AUTO; PADDING:30PX 20PX; TRANSITION: 0.3S; }
.THEATER-CONTAINER.CINEMA-MODE { GRID-TEMPLATE-COLUMNS:1FR; }
.THEATER-CONTAINER.CINEMA-MODE .PLAYLIST-WRAPPER { DISPLAY:NONE; }
.VIDEO-FRAME { POSITION:RELATIVE; ASPECT-RATIO:16/9; BACKGROUND:#000; BORDER-RADIUS:16PX; OVERFLOW:HIDDEN; BOX-SHADOW:0 20PX 50PX RGBA(0,0,0,0.5); BORDER:1PX SOLID RGBA(255,255,255,0.1); }
.CUSTOM-VIDEO { WIDTH:100%; HEIGHT:100%; }
.LOADING-OVERLAY { POSITION:ABSOLUTE; TOP:0; LEFT:0; WIDTH:100%; HEIGHT:100%; BACKGROUND:#000; Z-INDEX:5; DISPLAY:FLEX; FLEX-DIRECTION:COLUMN; ALIGN-ITEMS:CENTER; JUSTIFY-CONTENT:CENTER; }
.SPINNER { WIDTH:40PX; HEIGHT:40PX; BORDER:4PX SOLID RGBA(255,255,255,0.1); BORDER-LEFT-COLOR:VAR(--PRIMARY); BORDER-RADIUS:50%; ANIMATION:SPIN 1S LINEAR INFINITE; }
@KEYFRAMES SPIN { 100% { TRANSFORM:ROTATE(360DEG); } }
.AD-PLAYER-SLOT { MARGIN-TOP:15PX; TEXT-ALIGN:CENTER; BACKGROUND:#0A0A0C; PADDING:15PX; BORDER-RADIUS:12PX; BORDER:1PX SOLID RGBA(255,255,255,0.05); }
.AD-PLAYER-SLOT SMALL { DISPLAY:BLOCK; COLOR:#444; FONT-SIZE:0.7REM; MARGIN-BOTTOM:5PX; LETTER-SPACING:1PX; }
.PLAYER-NAV-CONTROLS { DISPLAY:FLEX; GAP:15PX; MARGIN-TOP:20PX; }
.NAV-BTN { FLEX:1; PADDING:14PX; BACKGROUND:RGBA(255,255,255,0.05); COLOR:WHITE; BORDER:1PX SOLID RGBA(255,255,255,0.1); BORDER-RADIUS:10PX; CURSOR:POINTER; FONT-WEIGHT:600; TRANSITION:0.3S; DISPLAY:FLEX; ALIGN-ITEMS:CENTER; JUSTIFY-CONTENT:CENTER; GAP:10PX; }
.NAV-BTN:HOVER:NOT(:DISABLED) { BACKGROUND:VAR(--PRIMARY); BORDER-COLOR:VAR(--PRIMARY); }
.NAV-BTN.DISABLED { OPACITY:0.3; CURSOR:NOT-ALLOWED; }
.VIDEO-INFO { MARGIN-TOP:30PX; }
.DRAMA-TITLE { FONT-SIZE:2REM; FONT-WEIGHT:800; MARGIN-BOTTOM:15PX; LINE-HEIGHT:1.2; TEXT-SHADOW:0 2PX 10PX RGBA(0,0,0,0.5); }
.META-BADGES { DISPLAY:FLEX; GAP:10PX; FLEX-WRAP:WRAP; MARGIN-BOTTOM:20PX; }
.META-BADGES SPAN { PADDING:5PX 12PX; BORDER-RADIUS:6PX; FONT-SIZE:0.8REM; FONT-WEIGHT:600; DISPLAY:INLINE-FLEX; ALIGN-ITEMS:CENTER; GAP:5PX; }
.BADGE-SERVER { BACKGROUND:VAR(--PRIMARY); COLOR:WHITE; }
.BADGE-RATING { BACKGROUND:#FFD700; COLOR:#000; }
.BADGE-INFO { BACKGROUND:RGBA(255,255,255,0.1); COLOR:#CCC; }
.TAGS-CONTAINER { DISPLAY:FLEX; GAP:8PX; FLEX-WRAP:WRAP; MARGIN-BOTTOM:25PX; }
.TAG-PILL { BACKGROUND:RGBA(255,255,255,0.05); BORDER:1PX SOLID RGBA(255,255,255,0.1); PADDING:6PX 16PX; BORDER-RADIUS:50PX; FONT-SIZE:0.85REM; COLOR:#CCC; TEXT-DECORATION:NONE; TRANSITION:0.3S; }
.TAG-PILL:HOVER { BACKGROUND:VAR(--PRIMARY); COLOR:WHITE; BORDER-COLOR:VAR(--PRIMARY); }
.SYNOPSIS-BOX H3 { FONT-SIZE:1.1REM; MARGIN-BOTTOM:10PX; COLOR:#FFF; BORDER-LEFT:4PX SOLID VAR(--PRIMARY); PADDING-LEFT:10PX; }
.SYNOPSIS-BOX P { COLOR:#CCC; LINE-HEIGHT:1.7; FONT-SIZE:1REM; }
.PLAYLIST-WRAPPER { BACKGROUND:#151518; BORDER-RADIUS:16PX; HEIGHT:700PX; DISPLAY:FLEX; FLEX-DIRECTION:COLUMN; BORDER:1PX SOLID RGBA(255,255,255,0.1); OVERFLOW:HIDDEN; }
.PLAYLIST-HEADER { PADDING:20PX; BACKGROUND:RGBA(0,0,0,0.2); BORDER-BOTTOM:1PX SOLID RGBA(255,255,255,0.05); }
.PH-SEARCH { POSITION:RELATIVE; MARGIN-TOP:10PX; }
.PH-SEARCH I { POSITION:ABSOLUTE; LEFT:12PX; TOP:50%; TRANSFORM:TRANSLATEY(-50%); COLOR:#666; }
.PH-SEARCH INPUT { WIDTH:100%; BACKGROUND:#0A0A0C; BORDER:1PX SOLID RGBA(255,255,255,0.1); PADDING:10PX 10PX 10PX 35PX; COLOR:WHITE; BORDER-RADIUS:8PX; FONT-SIZE:0.9REM; TRANSITION:0.3S; }
.PH-SEARCH INPUT:FOCUS { BORDER-COLOR:VAR(--PRIMARY); OUTLINE:NONE; }
.PLAYLIST-SCROLL { FLEX:1; OVERFLOW-Y:AUTO; PADDING:10PX; }
.PLAYLIST-SCROLL::-WEBKIT-SCROLLBAR { WIDTH:5PX; }
.PLAYLIST-SCROLL::-WEBKIT-SCROLLBAR-THUMB { BACKGROUND:#444; BORDER-RADIUS:10PX; }
.EPS-ITEM { DISPLAY:FLEX; ALIGN-ITEMS:CENTER; GAP:15PX; WIDTH:100%; BACKGROUND:TRANSPARENT; BORDER:NONE; PADDING:15PX; COLOR:#EEE; CURSOR:POINTER; TEXT-ALIGN:LEFT; BORDER-RADIUS:10PX; TRANSITION:0.2S; MARGIN-BOTTOM:5PX; BORDER:1PX SOLID TRANSPARENT; }
.EPS-ITEM:HOVER { BACKGROUND:RGBA(255,255,255,0.05); }
.EPS-ITEM.ACTIVE { BACKGROUND:RGBA(229,9,20,0.1); BORDER-COLOR:VAR(--PRIMARY); }
.EPS-NUM { FONT-FAMILY:MONOSPACE; FONT-SIZE:1.1REM; COLOR:#666; FONT-WEIGHT:BOLD; WIDTH:30PX; }
.ACTIVE .EPS-NUM { COLOR:VAR(--PRIMARY); }
.EPS-NAME { FONT-WEIGHT:600; FONT-SIZE:0.95REM; }
.PAYWALL-OVERLAY { POSITION:ABSOLUTE; TOP:0; LEFT:0; WIDTH:100%; HEIGHT:100%; BACKGROUND:RGBA(0,0,0,0.95); DISPLAY:FLEX; FLEX-DIRECTION:COLUMN; ALIGN-ITEMS:CENTER; JUSTIFY-CONTENT:CENTER; Z-INDEX:10; }
.BTN-UPGRADE { BACKGROUND:VAR(--PRIMARY); COLOR:WHITE; PADDING:12PX 30PX; BORDER-RADIUS:50PX; TEXT-DECORATION:NONE; MARGIN-TOP:20PX; DISPLAY:INLINE-BLOCK; FONT-WEIGHT:BOLD; FONT-SIZE:1REM; BOX-SHADOW:0 5PX 20PX RGBA(229,9,20,0.4); }
.BTN-SECONDARY { BACKGROUND: #333; COLOR: WHITE; PADDING: 12PX 25PX; BORDER-RADIUS: 50PX; TEXT-DECORATION: NONE; DISPLAY: INLINE-BLOCK; FONT-WEIGHT: BOLD; FONT-SIZE: 1REM; BORDER: 1PX SOLID RGBA(255,255,255,0.2); TRANSITION: 0.3S; }
.BTN-SECONDARY:HOVER { BACKGROUND: #555; }
.SKIP-CONTROLS { DISPLAY:FLEX; GAP:5PX; MARGIN-RIGHT:5PX; }
.SWITCH-TOGGLE { DISPLAY:FLEX; ALIGN-ITEMS:CENTER; GAP:10PX; CURSOR:POINTER; FONT-SIZE:0.9REM; COLOR:#FFF; FONT-WEIGHT: 500; }
.SWITCH-TOGGLE INPUT { DISPLAY:NONE; }
.SWITCH-TOGGLE .SLIDER { WIDTH:42PX; HEIGHT:24PX; BACKGROUND:#333; BORDER-RADIUS:24PX; POSITION:RELATIVE; TRANSITION:0.3S; BORDER: 2PX SOLID #555; }
.SWITCH-TOGGLE .SLIDER:BEFORE { CONTENT:""; POSITION:ABSOLUTE; WIDTH:16PX; HEIGHT:16PX; BORDER-RADIUS:50%; BACKGROUND:WHITE; TOP:2PX; LEFT:2PX; TRANSITION:0.3S; }
.SWITCH-TOGGLE INPUT:CHECKED + .SLIDER { BACKGROUND:#00D2FF; BORDER-COLOR: #00D2FF; }
.SWITCH-TOGGLE INPUT:CHECKED + .SLIDER:BEFORE { TRANSFORM:TRANSLATEX(18PX); }
@MEDIA(MAX-WIDTH:900PX){ .THEATER-CONTAINER{GRID-TEMPLATE-COLUMNS:1FR;} .PLAYLIST-WRAPPER{HEIGHT:500PX;} }
@MEDIA(MAX-WIDTH:600PX){ .LABEL-TEXT { DISPLAY:NONE; } .SKIP-CONTROLS { BORDER:NONE; PADDING:0; MARGIN:0; } .TOOL-BTN { FONT-SIZE:0.8REM; PADDING:8PX; } .AD-PLAYER-SLOT { MARGIN: 10PX 0; PADDING: 10PX; } .DIVIDER-VERTICAL { DISPLAY: NONE; } .COMMENTS-SECTION { PADDING: 20PX; MARGIN-TOP: 20PX; } }
</STYLE>

<SCRIPT TYPE="APPLICATION/LD+JSON">
{
  "@CONTEXT": "HTTPS://SCHEMA.ORG",
  "@TYPE": "TVSERIES",
  "NAME": "<?= HTMLSPECIALCHARS($TITLE) ?>",
  "IMAGE": "<?= HTMLSPECIALCHARS($COVER) ?>",
  "DESCRIPTION": "<?= HTMLSPECIALCHARS(STRIP_TAGS($INTRO)) ?>",
  "AGGREGATERATING": {
    "@TYPE": "AGGREGATERATING",
    "RATINGVALUE": "<?= $RATING ?>",
    "BESTRATING": "10",
    "RATINGCOUNT": "<?= $VIEWS ?>"
  },
  "POTENTIALACTION": {
    "@TYPE": "WATCHACTION",
    "TARGET": "<?= (ISSET($_SERVER['HTTPS']) ? "HTTPS" : "HTTP") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]" ?>"
  }
}
</SCRIPT>
